version: '3'
services:
  web:
    build: './web'
    ports:
      - "9000:9000"

  orders:
    build: './orders'
    ports:
      - "9001:9000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  users:
    build: './users'
    ports:
      - "9002:9000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  products:
    build: './products'
    ports:
      - "9003:9000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices
  
  db:
    image: mongo
    ports:
      - "27018:27018"

  nginx:
    image: nginx:latest
    ports:
      - "9090:9090"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - users
      - orders
      - products